spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SINU
    username: sinu
    password: 12345678
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587