-- MySQL Script generated by MySQL Workbench
-- Jo 31 oct 2019 13:45:19 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SINU
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SINU
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SINU` DEFAULT CHARACTER SET big5 ;
USE `SINU` ;

-- -----------------------------------------------------
-- Table `SINU`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` ENUM('STUDENT', 'PROFESSOR', 'ADMIN') NULL,
  `group_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SINU`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `series_id` INT NULL,
  `year` INT NULL,
  `faculty` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SINU`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` ENUM('COURSE', 'LABORATORY', 'SEMINAR') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SINU`.`subjects_professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`subjects_professors` (
  `subject_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `SINU`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professor_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `SINU`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SINU`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`grades` (
  `id` INT NOT NULL,
  `grade` FLOAT NULL,
  `subject_professor_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `subject_professor_id_idx` (`subject_professor_id` ASC) VISIBLE,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `subject_professor_id`
    FOREIGN KEY (`subject_professor_id`)
    REFERENCES `SINU`.`subjects_professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `SINU`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SINU`.`timetable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SINU`.`timetable` (
  `subject_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `time` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`subject_id`, `group_id`),
  INDEX `group_id_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `subject_id`
    FOREIGN KEY (`subject_id`)
    REFERENCES `SINU`.`subjects_professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `SINU`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;